apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: policygen-certificates
  namespace: secret-test
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - policygen-certificates
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  name: policygen-certificates-channel
  namespace: secret-test
spec:
  type: Git
  pathname: https://github.com/giovannisciortino/policy-generator-certificates.git
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: /
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: policygen-certificates
  name: pol-gen-zcx-openshift-logging-sub
  namespace: secret-test
spec:
  allow:
    - apiVersion: policy.open-cluster-management.io/v1
      kinds:
        - "*"
    - apiVersion: apps.open-cluster-management.io/v1
      kinds:
        - PlacementRule
  channel: secret-test/policygen-certificates-channel
  placement:
    placementRef:
      kind: Placement
      name: policygen-certificates-placement
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  namespace: secret-test
  name: global
spec:
  clusterSet: global
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: policygen-certificates-placement
  namespace: secret-test
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
          - {key: name, operator: In, values: ["local-cluster"]}
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
